CXX=g++
CXXFLAGS=-O3 -g -std=c++0x -DHAVE_CONFIG_H

all:hfst-optimized-lookup

clean:
	rm -f hfst-optimized-lookup

install:all
	cp hfst-optimized-lookup ../../bin

uninstall:
	rm -f ../../bin/hfst-optimized-lookup
