all:
	make -C hfst-optimized-lookup-1.3
	make -C tagger

clean:
	make -C hfst-optimized-lookup-1.3 clean
	make -C tagger clean

install:all
	make -C hfst-optimized-lookup-1.3 install
	make -C tagger install

uninstall:
	make -C hfst-optimized-lookup-1.3 uninstall
	make -C tagger uninstall